import { randomUUID } from "node:crypto";
import mysql from "mysql2/promise";
// BUG-026: the seed script never loaded .env, so "pnpm seed:demo" failed
// with "DATABASE_URL is required" even when a perfectly good .env sat next
// to package.json. dotenv is already a dependency; load it before reading env.
import "dotenv/config";

const url = process.env.DATABASE_URL;
if (!url) throw new Error("DATABASE_URL is required to run the demo seed (set it in .env or the environment)");
const connection = await mysql.createConnection(url);
const id = () => randomUUID();

// Fictional development data only. Never use real personnel or operational data.
const aarav = id();
const ananya = id();
const vikram = id();
const roleIds = Object.fromEntries(["ADMIN", "MANAGER", "AUDITOR", "USER"].map(role => [role, id()]));
const permissionKeys = ["identity:create", "identity:read", "identity:update", "identity:revoke", "asset:create", "asset:read", "asset:assign", "asset:transfer", "asset:revoke", "audit:read", "policy:create", "policy:update", "administration:manage"];

await connection.beginTransaction();
for (const [name, roleId] of Object.entries(roleIds)) await connection.execute("INSERT INTO roles (id, name, description) VALUES (?, ?, ?)", [roleId, name, `Fictional demo role: ${name}`]);
for (const key of permissionKeys) await connection.execute("INSERT INTO permissions (id, `key`, description) VALUES (?, ?, ?)", [id(), key, `Fictional demo permission: ${key}`]);
for (const [identityId, displayName, did] of [[aarav, "Aarav Mehta", "did:demo:aarav-mehta"], [ananya, "Ananya Rao", "did:demo:ananya-rao"], [vikram, "Vikram Singh", "did:demo:vikram-singh"]]) {
  await connection.execute("INSERT INTO identities (id, displayName, organization, status, did) VALUES (?, ?, ?, 'ACTIVE', ?)", [identityId, displayName, "SAMPRAAN DEMO ORGANIZATION", did]);
}
await connection.execute("INSERT INTO identity_roles (identityId, roleId) VALUES (?, ?), (?, ?), (?, ?)", [aarav, roleIds.ADMIN, ananya, roleIds.MANAGER, vikram, roleIds.USER]);
const asset = id();
await connection.execute("INSERT INTO assets (id, assetId, name, type, classification, description, ownerIdentityId, custodianIdentityId, integrityHash, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'ACTIVE')", [asset, "ASSET-DEMO-FIRMWARE-001", "Restricted Firmware Package", "FIRMWARE", "HIGHLY_SENSITIVE", "Fictional development asset used for authorization tests.", aarav, ananya, "sha256:demo-integrity-hash"]);
await connection.execute("INSERT INTO asset_ownership (id, assetId, ownerIdentityId) VALUES (?, ?, ?)", [id(), asset, aarav]);
await connection.execute("INSERT INTO asset_custody (id, assetId, custodianIdentityId, reason) VALUES (?, ?, ?, ?)", [id(), asset, ananya, "Fictional demo custody assignment"]);
const policy = id();
await connection.execute("INSERT INTO policies (id, name, description, subjectRole, resourceType, action, assetClassification, effect, active) VALUES (?, ?, ?, ?, ?, ?, ?, 'DENY', true)", [policy, "Highly sensitive transfer guard", "Fictional demo policy: users cannot transfer highly sensitive assets.", "USER", "ASSET", "TRANSFER", "HIGHLY_SENSITIVE"]);
await connection.execute("INSERT INTO audit_events (id, actorIdentityId, action, resourceType, resourceId, decision, reason, metadata) VALUES (?, ?, ?, ?, ?, 'DENY', ?, ?)", [id(), vikram, "AUTHORIZATION_DENIED", "ASSET", "ASSET-DEMO-FIRMWARE-001", "Role USER cannot TRANSFER HIGHLY_SENSITIVE asset", JSON.stringify({ demo: true })]);
await connection.execute("INSERT INTO security_alerts (id, title, severity, status, identityId, assetId, description, riskScore) VALUES (?, ?, 'HIGH', 'OPEN', ?, ?, ?, ?)", [id(), "Suspicious Asset Access Pattern", vikram, asset, "Fictional demo alert generated by repeated denied requests.", 87]);
await connection.commit();
await connection.end();
console.log("Fictional SAMPRAAN demo data inserted.");
